#!/usr/bin/env python3
"""Merge results/*.csv rows into docs/results.md Table A.

Reads every CSV in results/ (ignoring README.md), dedupes by
(impl, width, scheme, process, payoff), and emits a Markdown table
keyed by scheme with columns per impl.
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
DOCS = ROOT / "docs"


def main() -> int:
    rows: list[dict[str, str]] = []
    for csv_path in sorted(RESULTS.glob("*.csv")):
        with csv_path.open() as f:
            reader = csv.DictReader(f)
            for r in reader:
                rows.append(r)

    if not rows:
        print("collate: no CSV rows found in results/", file=sys.stderr)
        return 1

    # Group by (scheme, process, width, payoff); column = impl.
    by_row: dict[tuple[str, str, str, str], dict[str, dict[str, str]]] = defaultdict(dict)
    impls: set[str] = set()
    for r in rows:
        key = (r["scheme"], r["process"], r["width"], r["payoff"])
        by_row[key][r["impl"]] = r
        impls.add(r["impl"])

    impl_order = sorted(impls)

    lines: list[str] = []
    lines.append("# kloeden benchmark results")
    lines.append("")
    lines.append("> Regenerated by `scripts/collate.py`. Do not edit by hand.")
    lines.append("")
    lines.append("## Table A (partial): scalar throughput on GBM")
    lines.append("")
    header = "| scheme | process | width | payoff | " + " | ".join(impl_order) + " |"
    sep = "|" + "---|" * (4 + len(impl_order))
    lines.append(header)
    lines.append(sep)
    for key in sorted(by_row.keys()):
        scheme, process, width, payoff = key
        row_cells = [scheme, process, width, payoff]
        for im in impl_order:
            r = by_row[key].get(im)
            if r is None:
                row_cells.append("not run")
            else:
                row_cells.append(f"mean={float(r['mc_mean']):.4f} ±{float(r['mc_stderr']):.4f}")
        lines.append("| " + " | ".join(row_cells) + " |")
    lines.append("")

    DOCS.mkdir(exist_ok=True)
    out = DOCS / "results.md"
    out.write_text("\n".join(lines))
    print(f"collate: wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
