#!/usr/bin/env python3
"""Merge results/*.csv rows into docs/results.md.

Emits Table A (throughput + correctness on smooth schemes) and Table C
(digital-delta correctness comparison) from the same CSV pool.

Table A rows have payoff="none". Table C rows have payoff starting with
"digital_" (digital_naive or digital_bel).
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
DOCS = ROOT / "docs"

ANALYTIC_DELTA = 0.019724


def fmt_throughput(paths_per_s: float) -> str:
    return f"{paths_per_s / 1e6:.1f} M path-steps/s"


def fmt_correctness(mean: float, stderr: float) -> str:
    return f"mean={mean:.4f} ±{stderr:.4f}"


def fmt_delta(mean: float, stderr: float) -> str:
    return f"Δ={mean:.6f} ±{stderr:.6f}"


def fmt_bias(mean: float) -> str:
    return f"{(mean - ANALYTIC_DELTA):+.6f}"


def main() -> int:
    rows: list[dict[str, str]] = []
    for csv_path in sorted(RESULTS.glob("*.csv")):
        with csv_path.open() as f:
            rows.extend(csv.DictReader(f))

    if not rows:
        print("collate: no CSV rows found in results/", file=sys.stderr)
        return 1

    table_a: dict[tuple[str, str, str, str], dict[str, dict[str, str]]] = defaultdict(dict)
    table_c: dict[tuple[str, str], dict[str, str]] = {}
    impls_a: set[str] = set()
    for r in rows:
        key = (r["scheme"], r["process"], r["width"], r["payoff"])
        impl = r["impl"]
        if r["payoff"] == "none":
            table_a[key][impl] = r
            impls_a.add(impl)
        elif r["payoff"].startswith("digital_"):
            ck = (r["payoff"], impl)
            table_c[ck] = r

    impl_order_a = sorted(impls_a)

    lines: list[str] = []
    lines.append("# kloeden benchmark results")
    lines.append("")
    lines.append("> Regenerated by `scripts/collate.py`. Do not edit by hand.")
    lines.append("")

    lines.append("## Table A: scalar throughput on GBM")
    lines.append("")
    lines.append("Single thread, pinned core, 20-rep median. Larger is better.")
    lines.append("")
    header = "| scheme | process | width | payoff | " + " | ".join(impl_order_a) + " |"
    sep = "|" + "---|" * (4 + len(impl_order_a))
    lines.append(header)
    lines.append(sep)
    for key in sorted(table_a.keys()):
        scheme, process, width, payoff = key
        cells = [scheme, process, width, payoff]
        for im in impl_order_a:
            r = table_a[key].get(im)
            if r is None:
                cells.append("not run")
            else:
                cells.append(fmt_throughput(float(r["paths_per_s"])))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")

    lines.append("### Correctness block (Table A)")
    lines.append("")
    lines.append("Sample mean and stderr of the terminal value. All impls run on the same Brownian-increment fixture so terminal means must agree within 4 stderrs (enforced by `scripts/verify.py`).")
    lines.append("")
    lines.append(header)
    lines.append(sep)
    for key in sorted(table_a.keys()):
        scheme, process, width, payoff = key
        cells = [scheme, process, width, payoff]
        for im in impl_order_a:
            r = table_a[key].get(im)
            if r is None:
                cells.append("not run")
            else:
                cells.append(fmt_correctness(float(r["mc_mean"]), float(r["mc_stderr"])))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")

    if table_c:
        lines.append(f"## Table C: digital-delta correctness (GBM, K = S_0, analytic Δ = {ANALYTIC_DELTA:.6f})")
        lines.append("")
        lines.append("Naive pathwise-diff returns 0 per path (Dirac in `f'`); BEL constant-flow weight delivers unbiased estimates within 4σ of analytic. Elworthy's symbolic-BEL column is deferred pending a crates.io release that exposes `from_paths::bel_delta_constant_flow_from_paths`.")
        lines.append("")
        lines.append("| payoff | impl | Δ estimate | bias vs analytic |")
        lines.append("|---|---|---|---|")
        for (payoff, impl) in sorted(table_c.keys()):
            r = table_c[(payoff, impl)]
            mean = float(r["mc_mean"])
            stderr = float(r["mc_stderr"])
            lines.append(f"| {payoff} | {impl} | {fmt_delta(mean, stderr)} | {fmt_bias(mean)} |")
        lines.append("")

    DOCS.mkdir(exist_ok=True)
    out = DOCS / "results.md"
    out.write_text("\n".join(lines))
    print(f"collate: wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
